const MAX_LINE_THICKNESS = 50;

export const MIN_LINE_THICKNESS = 1;
export const LINE_THICKNESS_RANGE = MAX_LINE_THICKNESS - MIN_LINE_THICKNESS;
export const THICKNESS_INCREMENT = 0.5;
export const MIN_SMOOTHING_FACTOR = 0.87;
export const INITIAL_SMOOTHING_FACTOR = 0.85;
export const WEIGHT_SPREAD = 10;
export const INITIAL_THICKNESS = 2;
